pipelines:
  default:
    - step:
        name: Build and test
        image: python:2.7
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python setup.py sdist
        artifacts:
          - dist/**
    - step:
        name: Deploy
        image: google/cloud-sdk:alpine
        trigger: manual
        script:
          # Authenticating with the service account key file
          - echo $GCLOUD_API_KEYFILE | base64 --decode --ignore-garbage > ./gcloud-api-key.json
          - gcloud auth activate-service-account --key-file gcloud-api-key.json
          # Linking to the Google Cloud project
          - gcloud config set project $GCLOUD_PROJECT
          - gsutil
